resources:
- name: git-repository
  type: git
  source:
    uri: https://github.com/scottmuc/canipair.git

- name: pez-pcf-beta
  type: cf
  source:
    api: https://api.run.pcfbeta.io
    username: smuc-ci
    password: ((smuc_ci_password))
    organization: pivot-smuc
    space: development
    skip_cert_check: false

jobs:
- name: deploy
  plan:
  - get: git-repository
    trigger: true
  - put: pez-pcf-beta
    params:
      manifest: git-repository/manifest.yml
      environment_variables:
        SLACK_API_TOKEN: ((slack_api_token))
